const listaPresentesCasamento = [
  {
    id: 1,
    name: '🍷 Kit Noite do Vinho',
    description: 'Para brindar o amor, maratonar séries e fingir que entendemos de vinho.',
    price: 189.9,
    image: '/presentes/kit-vinho.jpg',
    available: true,
  },
  {
    id: 2,
    name: '☕ Cafeteira dos Sonhos',
    description: 'Porque todo casamento feliz começa com café.',
    price: 229.9,
    image: '/presentes/cafeteira.jpg',
    available: true,
  },
  {
    id: 3,
    name: '🍽️ Aparelho de Jantar Elegante',
    description: 'Para receber visitas com cara de casal adulto responsável.',
    price: 349.9,
    image: '/presentes/aparelho-jantar.jpg',
    available: true,
  },
  {
    id: 4,
    name: '🛏️ Jogo de Cama Fofinho',
    description: 'Conforto nível máximo para os domingos de preguiça.',
    price: 279.9,
    image: '/presentes/jogo-cama.jpg',
    available: true,
  },
  {
    id: 5,
    name: '🍳 Conjunto de Panelas',
    description: 'Para as receitas incríveis e também para o miojo caprichado.',
    price: 599.9,
    image: '/presentes/panelas.jpg',
    available: true,
  },
  {
    id: 6,
    name: '🥂 Jogo de Taças',
    description: 'Para celebrar as pequenas conquistas e os grandes boletos pagos.',
    price: 189.9,
    image: '/presentes/tacas.jpg',
    available: true,
  },
  {
    id: 7,
    name: '🧺 Kit Toalhas de Banho',
    description: 'Toalhas bonitas para a casa ficar com cara de hotel chique.',
    price: 159.9,
    image: '/presentes/toalhas.jpg',
    available: true,
  },
  {
    id: 8,
    name: '🍞 Torradeira Charmosa',
    description: 'Para deixar o café da manhã mais gostoso e fotogênico.',
    price: 149.9,
    image: '/presentes/torradeira.jpg',
    available: true,
  },
  {
    id: 9,
    name: '🥤 Liquidificador Turbo',
    description: 'Smoothie fitness, vitamina ou brigadeiro, ele encara tudo.',
    price: 199.9,
    image: '/presentes/liquidificador.jpg',
    available: true,
  },
  {
    id: 10,
    name: '🧹 Robô Aspirador',
    description: 'Um pequeno herói da limpeza para salvar o casal da poeira.',
    price: 899.9,
    image: '/presentes/robo-aspirador.jpg',
    available: true,
  },
  {
    id: 11,
    name: '📺 TV para Sessão Pipoca',
    description: 'Essencial para filmes, séries e discussões sobre quem escolhe o próximo episódio.',
    price: 2499.9,
    image: '/presentes/tv.jpg',
    available: true,
  },
  {
    id: 12,
    name: '🕯️ Kit Jantar Romântico em Casa',
    description: 'Velas, clima especial e uma boa desculpa para pedir sobremesa.',
    price: 120,
    image: '/presentes/jantar-romantico.jpg',
    available: true,
  },
  {
    id: 13,
    name: '🛋️ Ajuda para Decorar o Cantinho',
    description: 'Uma forcinha para deixar o novo lar com a nossa cara.',
    price: 300,
    image: '/presentes/decoracao.jpg',
    available: true,
  },
  {
    id: 14,
    name: '🚿 Chuveiro Relax Edition',
    description: 'Para banhos longos, quentinhos e dignos de fim de novela.',
    price: 249.9,
    image: '/presentes/chuveiro.jpg',
    available: true,
  },
  {
    id: 15,
    name: '🍝 Noite da Massa',
    description: 'Um presente para futuros jantares cheios de carboidrato e amor.',
    price: 180,
    image: '/presentes/massa.jpg',
    available: true,
  },
  {
    id: 16,
    name: '🧀 Tábua de Frios Caprichada',
    description: 'Para impressionar as visitas ou só beliscar vendo série mesmo.',
    price: 139.9,
    image: '/presentes/tabua-frios.jpg',
    available: true,
  },
  {
    id: 17,
    name: '🌙 Luminária Aconchego',
    description: 'Luz gostosa para deixar o lar ainda mais acolhedor.',
    price: 109.9,
    image: '/presentes/luminaria.jpg',
    available: true,
  },
  {
    id: 18,
    name: '🧳 Ajuda para a Lua de Mel',
    description: 'Porque colecionar memórias é sempre um presentão.',
    price: 350,
    image: '/presentes/lua-de-mel.jpg',
    available: true,
  },
];

export { listaPresentesCasamento };
