const listaPresentesCasamento = [
  {
    id: '1',
    title: '🍷 Kit Noite do Vinho',
    description: 'Para brindar o amor, maratonar séries e fingir que entendemos de vinho.',
    unit_price: 189.9,
    quantity: 1,
    image: '/presentes/kit-vinho.jpg',
    available: true,
  },
  {
    id: '2',
    title: '☕ Cafeteira dos Sonhos',
    description: 'Porque todo casamento feliz começa com café.',
    unit_price: 229.9,
    quantity: 1,
    image: '/presentes/cafeteira.jpg',
    available: true,
  },
  {
    id: '3',
    title: '🍽️ Aparelho de Jantar Elegante',
    description: 'Para receber visitas com cara de casal adulto responsável.',
    unit_price: 349.9,
    quantity: 1,
    image: '/presentes/aparelho-jantar.jpg',
    available: true,
  },
  {
    id: '4',
    title: '🛏️ Jogo de Cama Fofinho',
    description: 'Conforto nível máximo para os domingos de preguiça.',
    unit_price: 279.9,
    quantity: 1,
    image: '/presentes/jogo-cama.jpg',
    available: true,
  },
  {
    id: '5',
    title: '🍳 Conjunto de Panelas',
    description: 'Para as receitas incríveis e também para o miojo caprichado.',
    unit_price: 599.9,
    quantity: 1,
    image: '/presentes/panelas.jpg',
    available: true,
  },
  {
    id: '6',
    title: '🥂 Jogo de Taças',
    description: 'Para celebrar as pequenas conquistas e os grandes boletos pagos.',
    unit_price: 189.9,
    quantity: 1,
    image: '/presentes/tacas.jpg',
    available: true,
  },
  {
    id: '7',
    title: '🧺 Kit Toalhas de Banho',
    description: 'Toalhas bonitas para a casa ficar com cara de hotel chique.',
    unit_price: 159.9,
    quantity: 1,
    image: '/presentes/toalhas.jpg',
    available: true,
  },
  {
    id: '8',
    title: '🍞 Torradeira Charmosa',
    description: 'Para deixar o café da manhã mais gostoso e fotogênico.',
    unit_price: 149.9,
    quantity: 1,
    image: '/presentes/torradeira.jpg',
    available: true,
  },
  {
    id: '9',
    title: '🥤 Liquidificador Turbo',
    description: 'Smoothie fitness, vitamina ou brigadeiro, ele encara tudo.',
    unit_price: 199.9,
    quantity: 1,
    image: '/presentes/liquidificador.jpg',
    available: true,
  },
  {
    id: '10',
    title: '🧹 Robô Aspirador',
    description: 'Um pequeno herói da limpeza para salvar o casal da poeira.',
    unit_price: 899.9,
    quantity: 1,
    image: '/presentes/robo-aspirador.jpg',
    available: true,
  },
  {
    id: '11',
    title: '📺 TV para Sessão Pipoca',
    description: 'Essencial para filmes, séries e discussões sobre quem escolhe o próximo episódio.',
    unit_price: 2499.9,
    quantity: 1,
    image: '/presentes/tv.jpg',
    available: true,
  },
  {
    id: '12',
    title: '🕯️ Kit Jantar Romântico em Casa',
    description: 'Velas, clima especial e uma boa desculpa para pedir sobremesa.',
    unit_price: 120,
    quantity: 1,
    image: '/presentes/jantar-romantico.jpg',
    available: true,
  },
  {
    id: '13',
    title: '🛋️ Ajuda para Decorar o Cantinho',
    description: 'Uma forcinha para deixar o novo lar com a nossa cara.',
    unit_price: 300,
    quantity: 1,
    image: '/presentes/decoracao.jpg',
    available: true,
  },
  {
    id: '14',
    title: '🚿 Chuveiro Relax Edition',
    description: 'Para banhos longos, quentinhos e dignos de fim de novela.',
    unit_price: 249.9,
    quantity: 1,
    image: '/presentes/chuveiro.jpg',
    available: true,
  },
  {
    id: '15',
    title: '🍝 Noite da Massa',
    description: 'Um presente para futuros jantares cheios de carboidrato e amor.',
    unit_price: 180,
    quantity: 1,
    image: '/presentes/massa.jpg',
    available: true,
  },
  {
    id: '16',
    title: '🧀 Tábua de Frios Caprichada',
    description: 'Para impressionar as visitas ou só beliscar vendo série mesmo.',
    unit_price: 139.9,
    quantity: 1,
    image: '/presentes/tabua-frios.jpg',
    available: true,
  },
  {
    id: '17',
    title: '🌙 Luminária Aconchego',
    description: 'Luz gostosa para deixar o lar ainda mais acolhedor.',
    unit_price: 109.9,
    quantity: 1,
    image: '/presentes/luminaria.jpg',
    available: true,
  },
  {
    id: '18',
    title: '🧳 Ajuda para a Lua de Mel',
    description: 'Porque colecionar memórias é sempre um presentão.',
    unit_price: 350,
    quantity: 1,
    image: '/presentes/lua-de-mel.jpg',
    available: true,
  },
];

export { listaPresentesCasamento };
