import {
  ImageGiftTravel,
  ImageGiftWine,
  ImageGiftCoffee,
  ImageGiftBed,
  ImageGiftFood,
  ImageGiftToaster,
  ImageGiftPs5,
  ImageGiftRobot,
  ImageGiftSpa,
  ImageGiftVip,
  ImageGiftGarden,
  ImageGiftSofa,
  ImageGiftGta,
  ImageGiftDishwasher,
  ImageGiftWashingMachine,
  ImageGiftCorinthians,
} from '../assets/images';

const listaPresentesCasamento = [
  {
    id: '1',
    title: '🍷 Kit Noite do Vinho',
    description: 'Para brindar o amor, maratonar séries e fingir que entendemos de vinho.',
    unit_price: 180,
    quantity: 1,
    image: ImageGiftWine,
    available: true,
  },
  {
    id: '2',
    title: '☕ Cafeteira dos Sonhos',
    description: 'Porque a Carol é viciada em café.',
    unit_price: 130,
    quantity: 1,
    image: ImageGiftCoffee,
    available: true,
  },
  {
    id: '7',
    title: '💃 Aulas de Dança (para o Noivo)',
    description: 'A Carol já dança muito, já o Vitor precisa de umas aulas para não passar vergonha.',
    unit_price: 5,
    quantity: 3,
    image: '/presentes/cafeteira.jpg',
    available: true,
  },
  {
    id: '4',
    title: '🛏️ Jogo de Cama Fofinho',
    description: 'Conforto nível máximo para os domingos de preguiça.',
    unit_price: 80,
    quantity: 1,
    image: ImageGiftBed,
    available: true,
  },
  {
    id: '5',
    title: '🍣 Cota Rodízio de Japonês Premium',
    description:
      'Nós amamos comer! Ajude a financiar a nossa missão de dar prejuízo para o restaurante de sushi mais próximo.',
    unit_price: 220,
    quantity: 2,
    image: ImageGiftFood,
    available: true,
  },
  {
    id: '8',
    title: '🍞 Torradeira Charmosa',
    description: 'Para combinar com a cafeteira da Carol.',
    unit_price: 120,
    quantity: 1,
    image: ImageGiftToaster,
    available: true,
  },
  {
    id: '2',
    title: '🎮 Controle Extra de PS5',
    description: 'Para resolver nossas brigas no modo cooperativo, jogando It Takes Two.',
    unit_price: 380,
    quantity: 2,
    image: ImageGiftPs5,
    available: true,
  },
  {
    id: '10',
    title: '🧹 Robô Aspirador',
    description: 'Um pequeno grande herói do Vitor, pois ele odeia passar pano na casa.',
    unit_price: 880,
    quantity: 1,
    image: ImageGiftRobot,
    available: true,
  },
  {
    id: '18',
    title: '🧖‍♀️🧖‍♂️ Day Spa do Casal',
    description:
      'Um dia de relaxamento completo para o casal, com massagens e momentos de puro descanso no Espaço Julio Ganiko.',
    unit_price: 400,
    quantity: 2,
    image: ImageGiftSpa,
    available: true,
  },
  {
    id: '4',
    title: '🦅 Ingresso VIP para ver o Timão',
    description:
      'Um patrocínio para eu ir na Neo Química Arena ver o Corinthians (e deixar a Carol em paz assistindo as doramas dela).',
    unit_price: 240,
    quantity: 3,
    image: ImageGiftCorinthians,
    available: true,
  },
  {
    id: '18',
    title: '🧳 Ajuda para a Lua de Mel',
    description: 'Porque colecionar memórias é sempre um presentão.',
    unit_price: 500,
    quantity: 1,
    image: ImageGiftTravel,
    available: true,
  },
  {
    id: '25',
    title: '🥂 Acesso à Sala VIP no Aeroporto',
    description:
      'Para a gente começar a lua de mel comendo coxinha de graça e brindando antes mesmo do avião decolar.',
    unit_price: 300,
    quantity: 2,
    image: ImageGiftVip,
    available: true,
  },
  {
    id: '38',
    title: '🌿 Painel de Madeira para Jardim Vertical',
    description:
      'Um painel rústico bem lindão para a Carol pendurar as plantinhas dela. Fica um charme na varanda, traz a natureza pra perto e libera espaço no chão!',
    unit_price: 200,
    quantity: 2,
    image: ImageGiftGarden,
    available: true,
  },
  {
    id: '43',
    title: '🛋️ Sofá Retrátil "Nível Nuvem"',
    description: 'O verdadeiro coração da casa: o lugar oficial para a Carol maratonar os doramas.',
    unit_price: 250,
    quantity: 12,
    image: ImageGiftSofa,
    available: true,
  },
  {
    id: '44',
    title: '🎮 Jogo: GTA 6 (Pré-venda PS5)',
    description:
      'O lançamento mais esperado da década! Para o Vitor passar madrugadas online com os amigos e a Carol dar muita risada com o caos do jogo.',
    unit_price: 400,
    quantity: 1,
    image: ImageGiftGta,
    available: true,
  },
  {
    id: '45',
    title: '🍽️ Máquina Lava-Louças',
    description: 'A salvação do nosso casamento!',
    unit_price: 120,
    quantity: 10,
    image: ImageGiftDishwasher,
    available: true,
  },
  {
    id: '46',
    title: '🧺 Máquina de Lavar Roupa',
    description:
      'Para manter a casa em ordem, já que nosso tempo livre é dedicado a viagens e não a esfregar roupas.',
    unit_price: 180,
    quantity: 10,
    image: ImageGiftWashingMachine,
    available: true,
  },
];

export { listaPresentesCasamento };
